### ISSUE TITLE
fibonacci-numbers file not found

### ISSUE THREAD

**Issue by Kunal-2001** [TheAlgorithms/website#75] opened 2021-05-25 18:09 UTC
Hey
I am new to this repository and just started to set it up on my local machine. I have already installed all the dependencies and fetched all the algorithms, but by booting the server, an error has resulted that the Fibonacci-numbers file is not found.

![Screenshot (31)](https://user-images.githubusercontent.com/61347506/119546893-0aec0380-bdb2-11eb-802b-686c471299eb.png)

I couldn't find a connection to a communication channel, so I opened the issue.
It would be nice if anyone can help me resolve this.

**Comment by Panquesito7** [comment] 2021-05-25 20:24
> couldn't find a connection to a communication channel

You can join our [Discord server](https://discord.gg/c7MnfGFGa6) and ask for help. There are plenty of people who can help. 🙂

> just started to set it up on my local machine

Have you tried to use the [Gitpod Ready-to-Code](https://gitpod.io/#https://github.com/TheAlgorithms/website) service? It's much easier to set up than doing it locally. Try to use it, and see if the problem persists.

Thank you. 🙂

**Comment by Kunal-2001** [comment] 2021-05-26 07:05
Thanks, @Panquesito7  
Gitpod actually worked and was pretty easy to set up.

**Comment by maltejur** [comment] 2021-05-26 14:01
Nice to see that that worked. The error still shouldn't occur tho. I recently made changes to `fibonacci-numbers`, but I tried installing everything again now and for me it still worked. Maybe try to delete your current local folder and clone a completely new one to remove any files that shouldn't be there.

**Comment by Panquesito7** [comment] 2021-05-26 17:47
Closing this issue. Please re-open this issue if you think it should be open. Thanks.

**Comment by Kunal-2001** [comment] 2021-05-26 21:31
I tried to clone the repository again but still, the issue persists. While fetching the algorithms, I found a bug that displays the above warning in the terminal.

![Screenshot (33)](https://user-images.githubusercontent.com/61347506/119732803-4c55df00-be96-11eb-835a-21c8c11ab5f7.png)

After tinkering with the fetch-algorithms script it seems that the bug is with the C-Sharp repository. Under the searching category, **A-Star** as a folder is passed while the script is expecting a file with the ".cs" extension.

<image width="550" src="https://user-images.githubusercontent.com/61347506/119733507-43b1d880-be97-11eb-8014-5bf525f5c8db.png">

**Comment by Panquesito7** [comment] 2021-05-26 21:43
> clone the repository again but still, the issue persists

Is the `fibonacci-numbers` file available now? 🤔

**Comment by Kunal-2001** [comment] 2021-05-26 21:47
> > clone the repository again but still, the issue persists
> 
> Is the `fibonacci-numbers` file available now? 🤔

Nope

**Comment by maltejur** [comment] 2021-05-27 14:58
@Kunal-2001 yes, I have also noticed that error with A-Star, good job on finding the cause of that. I've opened a pr to fix that issue, but it shouldn't have caused the original error you get, it will just lead to c# A-Star not being included.

I've done everything in a windows vm again and now get the same error as you. I am working on fixing it now.

**Comment by Kunal-2001** [comment] 2021-05-27 15:27
@maltejur After checking both in Gitpod and local setup, I guess the main difference is that locally only algorithms available in the C# repository are saved in the JSON files. Also, the implementation object for a particular algorithm only contains C-sharp.
This might cause an error in changing the languages also.

**Comment by maltejur** [comment] 2021-05-27 15:29
Okay, it should work now (https://github.com/TheAlgorithms/website/commit/828ce984ce9ff8f21cec85fb08fde1fd1c4f097d). The error was the windows path seperator (`\\` instead of `/`). Can you try again?

The fix for the other error also got merged btw. https://github.com/TheAlgorithms/C-Sharp/pull/225

**Comment by Kunal-2001** [comment] 2021-05-27 15:41
Yeah, now it's working fine 👍
Is there any issue I can work on ??

**Comment by maltejur** [comment] 2021-05-27 16:40
If you have any ideas for the website, you can of course work on those. I have been working a bit on [this branch](https://github.com/TheAlgorithms/website/compare/improve_seo) to improve SEO via metadata and such things. If you are experienced in that, you can try to improve that. Besides from that, the internationalization still needs to be implemented for that branch. You could also try to do that (that is a bit complicated, you can see example [here](https://github.com/TheAlgorithms/website/blob/main/components/editPage/addTranslation/index.tsx) and [here](https://github.com/TheAlgorithms/website/blob/828ce984ce9ff8f21cec85fb08fde1fd1c4f097d/public/locales/en/common.json#L56), if you have questions just ask).

**Comment by maltejur** [comment] 2021-05-27 16:44
Another idea you could work on is to add a icon to algorithms that have a explanation text, so that you see that right when you browse.

Somewhere here:
![aisubtgoiuasbg](https://user-images.githubusercontent.com/48161361/119864901-a2646a00-bf0a-11eb-9161-aed1def933fb.png)

**Closed as completed by maltejur** 2021-05-27 16:45 UTC
Labels: bug
