### ISSUE TITLE
[BUG] Vercel tests are failing

### ISSUE THREAD

**Issue by Panquesito7** [TheAlgorithms/website#174] opened 2022-09-05 04:13 UTC
### Description of the bug

It appears all the Vercel tests are failing, which prevents the website from being updated and deployed.

**Comment by maltejur** [comment] 2022-09-07 20:49
The build result is just getting too large due to more languages and algorithms being added. This is an architectural problem and can't be solved that easily. I currently don't have much time but I'll try to find a fix when I find the time.

**Comment by Panquesito7** [comment] 2022-09-08 02:34
Yeah. Maybe we should use a database because the list won't stop growing.
Let me know if you need any help with that or anything else. :)

**Comment by maltejur** [comment] 2022-09-11 09:58
A database won't fix that problem, the problem is that the generated HTML files get too large. This could be fixed by using the SSR functionality of Next.js, so basically generating the HTML on-demand.

**Comment by Panquesito7** [comment] 2022-09-25 15:07
Should be already fixed on the [`dev`](https://github.com/TheAlgorithms/website/tree/dev) branch. There are still a few tweaks to be done before merging all the changes.
Thanks to @maltejur for working on this. 🚀

**Closed as completed** 2022-09-25 16:06 UTC
Labels: bug, dont-close
